### ISSUE TITLE
create components for the contact us page

### ISSUE THREAD

**Issue by yashshah2820** [iiitv/studybuddy-web#11]

**Comment by MilindGupta-Creator** [comment]
Hello, I would like to add the contact us page on your website.

**Comment by nlok5923** [comment]
if this issue is open @iiitv/project-maintainers I would like to work on this issue.

**Comment by theyashshahs** [comment]
Okay @nlok5923 GFI

**Comment by nlok5923** [comment]
@yashshah2820 Sir is there are any premade UI for contact us page which I can refer to implement the components. Or it would be really good if you can elaborate this issue a bit.

**Comment by theyashshahs** [comment]
@nlok I will mail you the designs

**Comment by nlok5923** [comment]
@yashshah2820 my student id : 201951107
